const quotes = [

{quote:"Stay hungry, stay foolish.",author:"Steve Jobs"},
{quote:"The future depends on what you do today.",author:"Mahatma Gandhi"},
{quote:"Life is what happens when you're busy making other plans.",author:"John Lennon"},
{quote:"Be yourself; everyone else is already taken.",author:"Oscar Wilde"},
{quote:"In the middle of difficulty lies opportunity.",author:"Albert Einstein"},
{quote:"Success is not final, failure is not fatal.",author:"Winston Churchill"},
{quote:"What we think, we become.",author:"Buddha"},
{quote:"Knowing yourself is the beginning of all wisdom.",author:"Aristotle"},
{quote:"The journey of a thousand miles begins with one step.",author:"Lao Tzu"},
{quote:"Well done is better than well said.",author:"Benjamin Franklin"},

{quote:"Act as if what you do makes a difference. It does.",author:"William James"},
{quote:"Everything you've ever wanted is on the other side of fear.",author:"George Addair"},
{quote:"Dream big and dare to fail.",author:"Norman Vaughan"},
{quote:"Turn your wounds into wisdom.",author:"Oprah Winfrey"},
{quote:"Happiness depends upon ourselves.",author:"Aristotle"},
{quote:"It always seems impossible until it's done.",author:"Nelson Mandela"},
{quote:"The purpose of our lives is to be happy.",author:"Dalai Lama"},
{quote:"If opportunity doesn't knock, build a door.",author:"Milton Berle"},
{quote:"The best way to predict the future is to create it.",author:"Peter Drucker"},
{quote:"Do what you can, with what you have, where you are.",author:"Theodore Roosevelt"},

{quote:"Success usually comes to those who are too busy to be looking for it.",author:"Henry David Thoreau"},
{quote:"Don't watch the clock; do what it does. Keep going.",author:"Sam Levenson"},
{quote:"Believe you can and you're halfway there.",author:"Theodore Roosevelt"},
{quote:"Opportunities don't happen. You create them.",author:"Chris Grosser"},
{quote:"The secret of getting ahead is getting started.",author:"Mark Twain"},
{quote:"Quality is not an act, it is a habit.",author:"Aristotle"},
{quote:"If you can dream it, you can do it.",author:"Walt Disney"},
{quote:"Success is walking from failure to failure with no loss of enthusiasm.",author:"Winston Churchill"},
{quote:"The harder I work, the luckier I get.",author:"Samuel Goldwyn"},
{quote:"Do one thing every day that scares you.",author:"Eleanor Roosevelt"},

{quote:"You miss 100% of the shots you don't take.",author:"Wayne Gretzky"},
{quote:"Try not to become a man of success but rather a man of value.",author:"Albert Einstein"},
{quote:"Start where you are. Use what you have. Do what you can.",author:"Arthur Ashe"},
{quote:"Great things are done by a series of small things brought together.",author:"Vincent van Gogh"},
{quote:"Don't count the days, make the days count.",author:"Muhammad Ali"},
{quote:"Believe in your infinite potential.",author:"Roy T. Bennett"},
{quote:"Make each day your masterpiece.",author:"John Wooden"},
{quote:"The best revenge is massive success.",author:"Frank Sinatra"},
{quote:"Success is a journey, not a destination.",author:"Arthur Ashe"},
{quote:"Never bend your head. Always hold it high.",author:"Helen Keller"},

{quote:"The only way to do great work is to love what you do.",author:"Steve Jobs"},
{quote:"Go confidently in the direction of your dreams.",author:"Henry David Thoreau"},
{quote:"The power of imagination makes us infinite.",author:"John Muir"},
{quote:"Keep your face always toward the sunshine.",author:"Walt Whitman"},
{quote:"Nothing will work unless you do.",author:"Maya Angelou"},
{quote:"Light tomorrow with today.",author:"Elizabeth Barrett Browning"},
{quote:"A goal is a dream with a deadline.",author:"Napoleon Hill"},
{quote:"If you want to lift yourself up, lift up someone else.",author:"Booker T. Washington"},
{quote:"Courage is grace under pressure.",author:"Ernest Hemingway"},
{quote:"What lies behind us and what lies before us are tiny matters compared to what lies within us.",author:"Ralph Waldo Emerson"},
,
{quote:"Believe in yourself and all that you are.",author:"Christian D. Larson"},
{quote:"Success is getting what you want. Happiness is wanting what you get.",author:"Dale Carnegie"},
{quote:"The only limit to our realization of tomorrow is our doubts of today.",author:"Franklin D. Roosevelt"},
{quote:"Do not wait to strike till the iron is hot; but make it hot by striking.",author:"William Butler Yeats"},
{quote:"You become what you believe.",author:"Oprah Winfrey"},
{quote:"The future belongs to those who believe in the beauty of their dreams.",author:"Eleanor Roosevelt"},
{quote:"Aim for the moon. If you miss, you may hit a star.",author:"W. Clement Stone"},
{quote:"Every accomplishment starts with the decision to try.",author:"John F. Kennedy"},
{quote:"Perseverance is not a long race; it is many short races one after another.",author:"Walter Elliot"},
{quote:"Success is where preparation and opportunity meet.",author:"Bobby Unser"},

{quote:"It does not matter how slowly you go as long as you do not stop.",author:"Confucius"},
{quote:"Hardships often prepare ordinary people for an extraordinary destiny.",author:"C.S. Lewis"},
{quote:"You are never too old to set another goal or dream a new dream.",author:"C.S. Lewis"},
{quote:"Success is not the key to happiness. Happiness is the key to success.",author:"Albert Schweitzer"},
{quote:"Don't be pushed around by the fears in your mind.",author:"Roy T. Bennett"},
{quote:"The way to get started is to quit talking and begin doing.",author:"Walt Disney"},
{quote:"If you're going through hell, keep going.",author:"Winston Churchill"},
{quote:"The expert in anything was once a beginner.",author:"Helen Hayes"},
{quote:"Everything has beauty, but not everyone sees it.",author:"Confucius"},
{quote:"To succeed in life, you need two things: ignorance and confidence.",author:"Mark Twain"},

{quote:"A person who never made a mistake never tried anything new.",author:"Albert Einstein"},
{quote:"Success is liking yourself, liking what you do, and liking how you do it.",author:"Maya Angelou"},
{quote:"You only live once, but if you do it right, once is enough.",author:"Mae West"},
{quote:"Don't let yesterday take up too much of today.",author:"Will Rogers"},
{quote:"The best preparation for tomorrow is doing your best today.",author:"H. Jackson Brown Jr."},
{quote:"If you want to achieve greatness stop asking for permission.",author:"Anonymous"},
{quote:"Doubt kills more dreams than failure ever will.",author:"Suzy Kassem"},
{quote:"Every day may not be good, but there is something good in every day.",author:"Alice Morse Earle"},
{quote:"Life isn't about finding yourself. Life is about creating yourself.",author:"George Bernard Shaw"},
{quote:"A winner is a dreamer who never gives up.",author:"Nelson Mandela"},

{quote:"The greatest glory in living lies not in never falling, but in rising every time we fall.",author:"Nelson Mandela"},
{quote:"Keep your eyes on the stars and your feet on the ground.",author:"Theodore Roosevelt"},
{quote:"Failure is simply the opportunity to begin again, this time more intelligently.",author:"Henry Ford"},
{quote:"Nothing is impossible. The word itself says 'I'm possible!'",author:"Audrey Hepburn"},
{quote:"Be the change that you wish to see in the world.",author:"Mahatma Gandhi"},
{quote:"A journey of a thousand miles begins with a single step.",author:"Lao Tzu"},
{quote:"Success seems to be connected with action.",author:"Conrad Hilton"},
{quote:"Life is either a daring adventure or nothing at all.",author:"Helen Keller"},
{quote:"Our greatest weakness lies in giving up.",author:"Thomas Edison"},
{quote:"You don't have to be great to start, but you have to start to be great.",author:"Zig Ziglar"},

{quote:"The mind is everything. What you think you become.",author:"Buddha"},
{quote:"If you tell the truth, you don't have to remember anything.",author:"Mark Twain"},
{quote:"The only impossible journey is the one you never begin.",author:"Tony Robbins"},
{quote:"Happiness is not by chance, but by choice.",author:"Jim Rohn"},
{quote:"Don't wish it were easier. Wish you were better.",author:"Jim Rohn"},
{quote:"Either you run the day or the day runs you.",author:"Jim Rohn"},
{quote:"The difference between ordinary and extraordinary is that little extra.",author:"Jimmy Johnson"},
{quote:"Never let the fear of striking out keep you from playing the game.",author:"Babe Ruth"},
{quote:"The successful warrior is the average man with laser-like focus.",author:"Bruce Lee"},
{quote:"Knowing is not enough; we must apply. Willing is not enough; we must do.",author:"Johann Wolfgang von Goethe"},
,
{quote:"The greatest wealth is to live content with little.",author:"Plato"},
{quote:"An unexamined life is not worth living.",author:"Socrates"},
{quote:"The only true wisdom is in knowing you know nothing.",author:"Socrates"},
{quote:"What you get by achieving your goals is not as important as what you become by achieving your goals.",author:"Zig Ziglar"},
{quote:"People often say that motivation doesn't last. Well, neither does bathing; that's why we recommend it daily.",author:"Zig Ziglar"},
{quote:"Expect the best. Prepare for the worst. Capitalize on what comes.",author:"Zig Ziglar"},
{quote:"You can have everything in life you want if you will just help enough other people get what they want.",author:"Zig Ziglar"},
{quote:"When one door of happiness closes, another opens.",author:"Helen Keller"},
{quote:"Optimism is the faith that leads to achievement.",author:"Helen Keller"},
{quote:"Alone we can do so little; together we can do so much.",author:"Helen Keller"},

{quote:"Keep your face to the sunshine and you cannot see a shadow.",author:"Helen Keller"},
{quote:"Do what you feel in your heart to be right.",author:"Eleanor Roosevelt"},
{quote:"No one can make you feel inferior without your consent.",author:"Eleanor Roosevelt"},
{quote:"With the new day comes new strength and new thoughts.",author:"Eleanor Roosevelt"},
{quote:"The only thing we have to fear is fear itself.",author:"Franklin D. Roosevelt"},
{quote:"Energy and persistence conquer all things.",author:"Benjamin Franklin"},
{quote:"Well begun is half done.",author:"Aristotle"},
{quote:"Patience is bitter, but its fruit is sweet.",author:"Aristotle"},
{quote:"The roots of education are bitter, but the fruit is sweet.",author:"Aristotle"},
{quote:"We are what we repeatedly do. Excellence, then, is not an act but a habit.",author:"Aristotle"},

{quote:"Act without expectation.",author:"Lao Tzu"},
{quote:"Nature does not hurry, yet everything is accomplished.",author:"Lao Tzu"},
{quote:"Silence is a source of great strength.",author:"Lao Tzu"},
{quote:"Health is the greatest possession.",author:"Lao Tzu"},
{quote:"Knowing others is intelligence; knowing yourself is true wisdom.",author:"Lao Tzu"},
{quote:"The secret of change is to focus all your energy not on fighting the old but on building the new.",author:"Socrates"},
{quote:"The harder the conflict, the greater the triumph.",author:"George Washington"},
{quote:"Perseverance and spirit have done wonders in all ages.",author:"George Washington"},
{quote:"Associate yourself with men of good quality.",author:"George Washington"},
{quote:"It is better to offer no excuse than a bad one.",author:"George Washington"},

{quote:"I never dreamed about success. I worked for it.",author:"Estee Lauder"},
{quote:"Success is a state of mind.",author:"Joyce Brothers"},
{quote:"If you want to make your dreams come true, the first thing you have to do is wake up.",author:"J.M. Power"},
{quote:"Don't limit your challenges. Challenge your limits.",author:"Jerry Dunn"},
{quote:"A little progress each day adds up to big results.",author:"Satya Nani"},
{quote:"Discipline is the bridge between goals and accomplishment.",author:"Jim Rohn"},
{quote:"Take care of your body. It's the only place you have to live.",author:"Jim Rohn"},
{quote:"Success is nothing more than a few simple disciplines practiced every day.",author:"Jim Rohn"},
{quote:"Motivation is what gets you started. Habit is what keeps you going.",author:"Jim Rohn"},
{quote:"Learn to be thankful for what you already have.",author:"Roy T. Bennett"},

{quote:"Be brave to stand for what you believe in.",author:"Roy T. Bennett"},
{quote:"Start each day with a positive thought.",author:"Roy T. Bennett"},
{quote:"Do not fear failure but rather fear not trying.",author:"Roy T. Bennett"},
{quote:"Success is not how high you have climbed, but how you make a positive difference.",author:"Roy T. Bennett"},
{quote:"Never lose hope. Storms make people stronger.",author:"Roy T. Bennett"},
{quote:"The only source of knowledge is experience.",author:"Albert Einstein"},
{quote:"Strive not to be a success, but rather to be of value.",author:"Albert Einstein"},
{quote:"Life is like riding a bicycle. To keep your balance, you must keep moving.",author:"Albert Einstein"},
{quote:"Imagination is more important than knowledge.",author:"Albert Einstein"},
{quote:"Try not to become a person of success, but rather a person of value.",author:"Albert Einstein"},
,
{quote:"Success is not measured by what you accomplish, but by the opposition you have encountered.",author:"Orison Swett Marden"},
{quote:"The golden opportunity you are seeking is in yourself.",author:"Orison Swett Marden"},
{quote:"There is no elevator to success. You have to take the stairs.",author:"Zig Ziglar"},
{quote:"What lies behind us and what lies before us are tiny matters compared to what lies within us.",author:"Ralph Waldo Emerson"},
{quote:"Make the most of yourself, for that is all there is of you.",author:"Ralph Waldo Emerson"},
{quote:"Do not go where the path may lead, go instead where there is no path and leave a trail.",author:"Ralph Waldo Emerson"},
{quote:"Nothing great was ever achieved without enthusiasm.",author:"Ralph Waldo Emerson"},
{quote:"To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",author:"Ralph Waldo Emerson"},
{quote:"Our lives begin to end the day we become silent about things that matter.",author:"Martin Luther King Jr."},
{quote:"Faith is taking the first step even when you don't see the whole staircase.",author:"Martin Luther King Jr."},

{quote:"The time is always right to do what is right.",author:"Martin Luther King Jr."},
{quote:"Darkness cannot drive out darkness; only light can do that.",author:"Martin Luther King Jr."},
{quote:"Forgiveness is not an occasional act; it is a constant attitude.",author:"Martin Luther King Jr."},
{quote:"If you cannot fly then run, if you cannot run then walk.",author:"Martin Luther King Jr."},
{quote:"I have learned over the years that when one's mind is made up, this diminishes fear.",author:"Rosa Parks"},
{quote:"Each person must live their life as a model for others.",author:"Rosa Parks"},
{quote:"You must never be fearful about what you are doing when it is right.",author:"Rosa Parks"},
{quote:"Memories of our lives, our works and our deeds will continue in others.",author:"Rosa Parks"},
{quote:"It always seems impossible until it's done.",author:"Nelson Mandela"},
{quote:"May your choices reflect your hopes, not your fears.",author:"Nelson Mandela"},

{quote:"Education is the most powerful weapon which you can use to change the world.",author:"Nelson Mandela"},
{quote:"A good head and a good heart are always a formidable combination.",author:"Nelson Mandela"},
{quote:"There is nothing like returning to a place that remains unchanged to find the ways in which you yourself have altered.",author:"Nelson Mandela"},
{quote:"Resentment is like drinking poison and hoping it will kill your enemies.",author:"Nelson Mandela"},
{quote:"Do not judge me by my successes, judge me by how many times I fell down and got back up again.",author:"Nelson Mandela"},
{quote:"Success is falling nine times and getting up ten.",author:"Jon Bon Jovi"},
{quote:"The best way to gain self-confidence is to do what you are afraid to do.",author:"Swati Sharma"},
{quote:"Never let success get to your head and never let failure get to your heart.",author:"Drake"},
{quote:"A river cuts through rock not because of its power, but because of its persistence.",author:"James N. Watkins"},
{quote:"Small deeds done are better than great deeds planned.",author:"Peter Marshall"},

{quote:"You don't find the happy life. You make it.",author:"Camilla Eyring Kimball"},
{quote:"Happiness is not something ready made. It comes from your own actions.",author:"Dalai Lama"},
{quote:"Calm mind brings inner strength and self-confidence.",author:"Dalai Lama"},
{quote:"Remember that sometimes not getting what you want is a wonderful stroke of luck.",author:"Dalai Lama"},
{quote:"Love and compassion are necessities, not luxuries.",author:"Dalai Lama"},
{quote:"The roots of all goodness lie in the soil of appreciation for goodness.",author:"Dalai Lama"},
{quote:"Judge your success by what you had to give up in order to get it.",author:"Dalai Lama"},
{quote:"If you want others to be happy, practice compassion.",author:"Dalai Lama"},
{quote:"Wherever you go, go with all your heart.",author:"Confucius"},
{quote:"The man who moves a mountain begins by carrying away small stones.",author:"Confucius"},

{quote:"It does not matter how slowly you go as long as you do not stop.",author:"Confucius"},
{quote:"Our greatest glory is not in never falling, but in rising every time we fall.",author:"Confucius"},
{quote:"When anger rises, think of the consequences.",author:"Confucius"},
{quote:"Respect yourself and others will respect you.",author:"Confucius"},
{quote:"The will to win, the desire to succeed, the urge to reach your full potential are the keys to personal excellence.",author:"Confucius"},
{quote:"Believe you can and you're halfway there.",author:"Theodore Roosevelt"},
{quote:"Keep your eyes on the stars and your feet on the ground.",author:"Theodore Roosevelt"},
{quote:"Do what you can, with what you have, where you are.",author:"Theodore Roosevelt"},
{quote:"Far and away the best prize that life offers is the chance to work hard at work worth doing.",author:"Theodore Roosevelt"},
{quote:"Nothing worth having comes easy.",author:"Theodore Roosevelt"}
];